USE delightdb;

INSERT INTO lkp_category
        (category_name)
VALUES
        ("Food"),
        ("Fitness"),
        ("Music"),
        ("Tech"),
        ("Movies"),
        ("Reading"),
        ("Gaming"),
        ("Fashion"),
        ("Travel"),
        ("Politics"),
        ("Sports"),
        ("Anime/Cartoons")
;
INSERT INTO lkp_interests
        (interest_name, category_id)

VALUES
        ("Sushi", 1),
        ("Spaghetti", 1),
        ("Coffee", 1),
        ("Greek", 1),
        ("Ginger Shots", 1),
        ("Lasagna", 1),
        ("Tofu Scramble", 1),
        ("Kale Salads", 1),
        ("Smoothie", 1),
        ("IHOP Grand Slam", 1),
        ("Hiking", 2),
        ("Bodybuilding", 2),
        ("Calisthenics", 2),
        ("Jogging", 2),
        ("Yoga", 2),
        ("Pilates", 2),
        ("Cycling", 2),
        ("Martial Arts", 2),
        ("Water Aerobics", 2),
        ("Surfing", 2),
        ("Celine Dion", 3),
        ("Rihanna", 3),
        ("Drake", 3),
        ("The Rolling Stones", 3),
        ("Michael Jackson", 3),
        ("Elvis Presley", 3),
        ("Bob Dylan", 3),
        ("Eminem", 3),
        ("Jay-Z", 3),
        ("Beyonce", 3),
        ("Apple", 4),
        ("Android", 4),
        ("Facebook", 4),
        ("Snapchat", 4),
        ("Twitter", 4),
        ("Drones", 4),
        ("3D Printing", 4),
        ("Robotics", 4),
        ("Web Development", 4),
        ("The Dark Knight", 5),
        ("Deadpool", 5),
        ("The Notebook", 5),
        ("Men in Black", 5),
        ("Avengers: Endgame", 5),
        ("IT", 5),
        ("Pulp Fiction", 5),
        ("Black Hawk Down", 5),
        ("The Matrix", 5),
        ("The Shawshank Redemption", 5),
        ("The Alchemist", 6),
        ("48 Laws of Power", 6),
        ("Harry Potter(Books)", 6),
        ("Sapiens(Book)", 6),
        ("The Power of Habit", 6),
        ("Aurora Rising", 6),
        ("The Handmaid's Tale(Book)", 6),
        ("The Hitchhiker's Guide to the Galaxy", 6),
        ("To Kill a Mockingbird", 6),
        ("Where the Wild Things Are", 6),
        ("Mario Kart", 7),
        ("Super Smash Bros.", 7),
        ("The Legend of Zelda", 7),
        ("Halo", 7),
        ("God of War", 7),
        ("Gears of War", 7),
        ("Xbox One", 7),
        ("Playstation 4", 7),
        ("The Elder Scrolls: Skyrim", 7),
        ("Call of Duty", 7),
        ("Air Jordans", 8),
        ("Louis Vuittons", 8),
        ("Red Bottoms", 8),
        ("Victoria's Secret", 8),
        ("Adidas", 8),
        ("Fashion Nova", 8),
        ("Fenty", 8),
        ("Yeezy", 8),
        ("Nike", 8),
        ("Bonobos", 8),
        ("AirBnB", 9),
        ("Japan", 9),
        ("Greece", 9),
        ("Egypt", 9),
        ("Italy", 9),
        ("London", 9),
        ("The Great Wall of China", 9),
        ("The Eiffel Tower", 9),
        ("Iceland", 9),
        ("The Statue of Liberty", 9),
        ("Donald Trump", 10),
        ("Barack Obama", 10),
        ("Nancy Pelosi", 10),
        ("Democrat", 10),
        ("Republican", 10),
        ("House of Representatives", 10),
        ("Supreme Court", 10),
        ("US Senate", 10),
        ("2020 Election", 10),
        ("United Nations", 10),
        ("Football", 11),
        ("Basketball", 11),
        ("Tennis", 11),
        ("Soccer", 11),
        ("Golf", 11),
        ("Baseball", 11),
        ("Cricket", 11),
        ("Softball", 11),
        ("Rugby", 11),
        ("Volleyball", 11),
        ("My Hero Academia", 12),
        ("Dragon Ball Z", 12),
        ("Cowboy Bebop", 12),
        ("Fruits Basket", 12),
        ("Death Note", 12),
        ("Gurren Lagann", 12),
        ("Naruto", 12),
        ("Jojo's Bizarre Adventure", 12),
        ("The Seven Deadly Sins", 12),
        ("Ghost in the Shell", 12)
    ;

INSERT INTO prompts
        (prompt_string)

VALUES
        ("Out of these five choices, pick the one that either you have heard of or is the most appealing."),
        ("Good job! Pick another!"),
        ("Here's another one!"),
        ("Keep 'em coming y'all!"),
        ("Oh man, here we go again!"),
        ("I'll keep pitching 'em up, you keep knocking it out of the park!"),
        ("I'm impressed! Here's another one!"),
        ("You're good at this! Go again!"),
        ("Almost there! Pick again!"),
        ("Last One!")
;